name: posix
version: 6.0.0
homepage: https://github.com/onepub-dev/dart_posix
description: Exposes the POSIX api on OSx and Linux
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  ffi: ^2.0.1
  meta: ^1.7.0
  path: ^1.8.3
dev_dependencies: 
  cli_script: ^0.3.1
  ffigen: ^6.0.0
  lint_hard: ^3.0.0
  logger: ^1.3.0
  logging: ^1.1.1
  stack_trace: ^1.11.0
  test: ^1.16.2
  uuid: ^3.0.7
