name: posix
version: 2.0.0
homepage: https://github.com/bsutton/dart_posix
description: Exposes the POSIX api on OSx and Linux
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  ffi: ^1.0.0
dev_dependencies: 
  dcli: ^1.0.0
  pedantic: ^1.10.0
  test: ^1.16.2
  ffigen: ^2.0.0

# dependency_overrides:
#   dcli:
#     path: ../dcli

